import { PostsList } from 'components/posts-list';
import { trpc } from 'lib/trpc';
import { dehydrateQueries } from 'lib/trpc/dehydrate-queries';
import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';

const IndexPage: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ page }) => {
  const postsQuery = trpc.useQuery(['post.all', { page }]);

  if (postsQuery.isLoading && !postsQuery.data) {
    return <div>Loading...</div>;
  }

  if (postsQuery.isError || !postsQuery.data) {
    return <div>Something went wrong...</div>;
  }

  const hasMorePages = page * postsQuery.data.perPage < postsQuery.data.totalCount;

  return (
    <>
      <Head>
        <title>QuackerNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostsList posts={postsQuery.data.posts} hasMorePages={hasMorePages} nextPageUrl={`/news?p=${page + 1}`} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ctx => {
  const pageParam = parseInt(ctx.query.page as string, 10);
  const page = isNaN(pageParam) ? 1 : pageParam;

  const dataProps = await dehydrateQueries(ctx, async ssg => {
    await ssg.fetchQuery('post.all', { page });
  });

  return { props: { ...dataProps, page } };
};

export default IndexPage;
