import { AppHeader } from 'components/app-header';
import { PostsList } from 'components/posts-list';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  // const createComment = trpc.useMutation('comment.create');

  // const handleSubmit: React.FormEventHandler = async e => {
  //   e.preventDefault();

  //   const formData = new FormData(e.target as HTMLFormElement);

  //   await createComment.mutateAsync({
  //     postId: '1',
  //     content: formData.get('content') as string,
  //     authorId: '1',
  //   });
  // };

  return (
    <div>
      <Head>
        <title>QuackerNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4">
        <AppHeader />
        <PostsList />

        {/*
        <form onSubmit={handleSubmit}>
          <input type="hidden" name="postId" value="1" />
          <input name="content" required />

          <button>Create Comment</button>
        </form> */}
      </main>
    </div>
  );
};

export default Home;
